Feature/Byte Vec Deserialize Wrapper
BlackbirdHQ/atat pull request #68
Opened 2020-11-12 16:26 UTC by unizippro

Wrapper for deserializing a Vector of bytes like fx "+UUWLE:32AB6A7A4044".
Primarily done to parse bssid for [ublox-short-range-rs](https://github.com/BlackbirdHQ/ublox-short-range-rs/).
But this is kind of a catch all for any Non comma separated value in any AT command.

2020-11-12 19:02 UTC, MathiasKoch requested changes
A few small changes, but overall looks good.

I realize it is not quite the same case, 
but perhaps you could "un-ignore" the existing test-case for `Vec` and make that pass as well?

2020-11-12 19:02 UTC, MathiasKoch commented on serde_at/src/de/mod.rs
> +        assert_eq!(crate::from_str("+CCID: IMP_"), Ok(stru));
No reason for the extra wrapper here?

```suggestion
        let expectation = CharVec(
            heapless::Vec::from_slice(&['I', 'M', 'P', '_']).unwrap(),
        );
        assert_eq!(crate::from_str("+CCID: IMP_"), Ok(expectation));
```

2020-11-13 09:32 UTC, MathiasKoch commented on serde_at/src/de/seq.rs
>  pub struct SeqByteAccess<'a, 'b> {
Okay, i stand corrected on the `#[allow(clippy::module_name_repetitions)]`

2020-11-13 09:32 UTC, MathiasKoch commented on serde_at/src/de/mod.rs
> +/// let incomming: CommandStruct = from_str("+CCID: 4,IMP_MSG,-12")
```suggestion
/// let incoming: CommandStruct = from_str("+CCID: 4,IMP_MSG,-12")
```

2020-11-13 09:32 UTC, MathiasKoch commented on serde_at/src/de/mod.rs
> +/// assert_eq!(incomming, Ok(expected));
```suggestion
/// assert_eq!(incoming, Ok(expected));
```

2020-12-04 10:01 UTC, unizippro commented
Tarpaulin is crashing and i have no clue why this is the case.
Anyone who can offer any advice or help would be greatly appreciated!

2020-12-10 13:41 UTC, MathiasKoch approved these changes

2020-12-10 13:48 UTC, merged